flavor = "quarto"
line-width = 80

[format]
wrap = "semantic"
lang = "cs"

[format.no-break-abbreviations]
cs = ["2.", "1.", "3.", "4.", "5.", "6."]

[formatters]
r = "air"
python = "ruff"
javascript = "prettier"
typescript = "prettier"